/**
 * WARNING! 
 * Do not edit this file!
 * It has been generated from this source:
 * 
 *   primitive.frag
 * 
 * 2023-12-20T08:23:05.764Z
 */
const SHADER = "#version 300 es\n\nprecision mediump float;\n\nin vec4 varColor;\nout vec4 FragColor;\n\nvoid main() {\n    FragColor = varColor;\n}\n"
export default SHADER
