/**
 * WARNING! 
 * Do not edit this file!
 * It has been generated from this source:
 * 
 *   isometric.frag
 * 
 * 2023-12-20T08:23:05.764Z
 */
const SHADER = "#version 300 es\n\nprecision mediump float;\n\nuniform sampler2D uniTexture;\nin vec2 varUV;\nout vec4 FragColor;\n\nconst float EPSILON = 1.0 / 256.0;\n\nvoid main() {\n    vec4 color = texture(uniTexture, varUV);\n    if (color.a < EPSILON) discard;\n\n    FragColor = color;\n    float light = color.g < 0.001 ? 1.0 : 0.0;\n    FragColor =mix(vec4(varUV, 0, 1), vec4(light, light, light, 1), 0.5);\n    if (color.b < 0.001) FragColor = vec4(0,0,1,1);\n}"
export default SHADER
