/**
 * WARNING! 
 * Do not edit this file!
 * It has been generated from this source:
 * 
 *   isometric.vert
 * 
 * 2023-12-20T08:23:05.764Z
 */
const SHADER = "#version 300 es\n\nuniform vec3 uniCenter; // Coordonnées du centre de l'écran.\nuniform vec3 uniScale; // Échelle pour garder l'aspect ratio.\n\n// Instance\nlayout(location=0) in vec3 attPos;\nlayout(location=1) in vec4 attCell;\n\n// Vertex\nlayout(location=2) in vec2 attCorner;\nlayout(location=3) in vec2 attUV;\n\nout vec2 varUV;\n\nconst mat3 PROJ = mat3(\n    1.0, -1.0, 0.0,\n    0.5,  0.5, 0.0,\n    0.0,  0.0, 1.0\n);\n\nvoid main() {\n    varUV = attUV * attCell.zw + attCell.xy;\n    vec3 pos = PROJ * (attPos - uniCenter) + vec3(attCorner, 0.0);\n    gl_Position = vec4(pos * uniScale, 1.0);\n}"
export default SHADER
