/**
 * WARNING! 
 * Do not edit this file!
 * It has been generated from this source:
 * 
 *   sprites-painter.frag
 * 
 * 2023-12-20T08:23:05.764Z
 */
const SHADER = "#version 300 es\n\nprecision mediump float;\n\nuniform sampler2D uniTexture;\n\nin vec2 varUV;\nout vec4 FragColor;\n\nvoid main() {\n  FragColor = texture( uniTexture, varUV );\n  if (FragColor.a < 0.01) discard;\n}"
export default SHADER
