/**
 * WARNING! 
 * Do not edit this file!
 * It has been generated from this source:
 * 
 *   sprites-painter.vert
 * 
 * 2023-12-20T08:23:05.764Z
 */
const SHADER = "#version 300 es\n\nuniform mat4 uniCamera;\nin vec2 attPoint;\nin vec2 attAtlasXY;\nin vec2 attAtlasWH;\nin vec2 attCenter;\nin mat2 attTransform;\nin vec3 attPosition;\nout vec2 varUV;\n\nvoid main() {\n    varUV = attPoint * attAtlasWH + attAtlasXY;\n    vec3 point = vec3(attTransform * (attPoint - attCenter) * attAtlasWH, 0.0) + attPosition;\n    gl_Position = uniCamera * vec4(point, 1.0);\n}\n"
export default SHADER
